### ISSUE TITLE
Transaction Tab - Windows - Unable to select from drop downs

### ISSUE THREAD

**Issue by tipsy1** [jojapoppa/fedoratipscoin#24]
Transaction Tab - Windows - Unable to select from drop downs
On the heading drop downs that allow you to filter the list of transactions, I cannot use the mouse to select the entries in the combo box.

**Comment by goblinbomb** [comment]
This is fixed. I can use mouse to select options from dropdown.
![2018-03-19_09h16_36](https://user-images.githubusercontent.com/13028206/37571852-435ce8d4-2b56-11e8-8784-52c1ea1073c0.png)
