### ISSUE TITLE
logo in windows start and bottombar

### ISSUE THREAD

**Issue by k03nty** [jojapoppa/fedoratipscoin#28]
still old logo. would be nice if it could be the new hat. doesnt need to say tips. just the yellow hat:) minimalism is key!

**Comment by goblinbomb** [comment]
In the start menu showing the correct icon and so is in the bottombar
![2018-03-19_08h19_49](https://user-images.githubusercontent.com/13028206/37571253-65c43484-2b4e-11e8-9df4-4f716be4357d.png)
![2018-03-19_08h20_05](https://user-images.githubusercontent.com/13028206/37571254-6725bffa-2b4e-11e8-9963-c23e26cfcd0e.png)

.

**Comment by robotsoutofcontrol** [comment]
I think the install doesn't overwrite an **_existing_** Fedora icon in the taskbar (but it does in the start menu).  The start menu shows the yellow hat, the task bar the old one: 
![image](https://user-images.githubusercontent.com/4340080/37640647-b0cdfb00-2c6a-11e8-84c4-0ff7b56071a6.png)

Very minor thing and possibly tricky to debug. It seems that it maybe caches the icon somewhere.
