### ISSUE TITLE
Redirect bug report email

### ISSUE THREAD

**Issue by jojapoppa** [jojapoppa/fedoratipscoin#3]
Use this instead:

Proton mail detail is:
Username: tipsbugreports

(thanks goblinbomb!)

**Comment by goblinbomb** [comment]
Fixed. Now the bugreport goes to tipsbugreports@protonmail.com
![2018-03-19_09h18_33](https://user-images.githubusercontent.com/13028206/37571867-979a19da-2b56-11e8-8b76-bde1f0a3aa50.png)
