### ISSUE TITLE
Installer Icon Needs Replacing

### ISSUE THREAD

**Issue by tipsy1** [jojapoppa/fedoratipscoin#7]
When downloading and installing, the icon in the system tray needs to be updated:
![icon](https://user-images.githubusercontent.com/34650111/36949898-545d500c-2042-11e8-9670-27cc36eeeb96.PNG)

**Comment by goblinbomb** [comment]
This is fixed.
![2018-03-19_08h09_31](https://user-images.githubusercontent.com/13028206/37571150-e252eaf6-2b4c-11e8-9f2a-95efa6bb9cfe.png)
